name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-clj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-tests
        run: lein ci unit
      - name: upload-code-coverage-report
        uses: codecov/codecov-action@v1
        with:
          file: target/coverage/codecov.json

  test-cljs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-ws
        run: npm i ws
      - name: run-tests
        run: lein ci unit-cljs
